# Linux: Firefox
[[extensions]]
browser = "firefox"
profile = "~/.mozilla/firefox/XXXXXXXX.default"
names = ["ublock-origin", "sidebery", "vimium-ff", "darkreader"]

# Linux: Librewolf
[[extensions]]
browser = "firefox"
profile = "~/.librewolf/XXXXXXXX.default"
names = ["sidebery", "vimium-ff", "darkreader"]

# Linux: Chromium
[[extensions]]
browser = "chromium"
profile = "~/.config/chromium"
names = [
    "cjpalhdlnbpafiamejdnhcphjbkeiagm", # ublock-origin
    "dbepggeogbaibhgnhhndojpepiihcmeb", # vimium
    "eimadpbcbfnmbkopoojfekhnkhdbieeh", # darkreader
]

# Linux: Brave
[[extensions]]
browser = "chromium"
profile = "~/.config/BraveSoftware/Brave-Browser"
names = [
    "dbepggeogbaibhgnhhndojpepiihcmeb", # vimium
    "eimadpbcbfnmbkopoojfekhnkhdbieeh", # darkreader
]

# Edge on Windows
[[extensions]]
browser = "chromium"
profile = "Microsoft\\Edge"
names = [
    "cjpalhdlnbpafiamejdnhcphjbkeiagm", # ublock-origin
]

# Microsoft Edge on Windows
[[extensions]]
browser = "chromium"
profile = "Microsoft\\Edge"
names = [
    "cjpalhdlnbpafiamejdnhcphjbkeiagm", # ublock-origin
]

# Google Chrome on Windows
[[extensions]]
browser = "chromium"
profile = "Google\\Chrome"
names = [
    "cjpalhdlnbpafiamejdnhcphjbkeiagm", # ublock-origin
]

# Firefox on Windows
[[extensions]]
browser = "firefox"
profile = "C:\\Users\\Quickemu\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\u6bp8cmh.default-release"
names = [
    "ublock-origin",
]
